### PR TITLE
Update dependencies and make reloading more reliable.

### PR DESCRIPTION
**Pull request by Neopallium**
Updated the notify & libloading dependencies.

On Linux if the library file (inode) is deleted then inotify will stop sending events.  I think it is better to watch the parent folder.

Also only reload on `CLOSE_WRITE` and `CREATE` events.

### CODE REVIEW

**Comment by emoon** [comment]
hum... seems that appveyor fails to using a (very) old version of Rust :( If possible could you just try to replace the `appveyor` file with this one https://github.com/emoon/rust_minifb/blob/master/appveyor.yml just to make sure the CI passes.

**Comment by emoon** [comment]
Awesome! Thanks a lot for these fixes. I will publish a new version later today

**Comment by Neopallium** [comment]
@emoon Hold on the release.  Reloading on `WRITE` events on linux can cause problems, since sometimes hundreds of `WRITE` events are received.  I am going to try the `DebounceEvent` watcher.

**Comment by emoon** [comment]
Cool. Thanks for doing some fixes for this :)

**Comment by Boscop** [comment]
@Neopallium I have a question: In your post, it says "Also only reload on `CLOSE_WRITE` and `CREATE` events."
But in the diff it shows that you also reload on `WRITE` events, which are sent for all write operations that happen before the file is closed.
Why are you reloading also on `WRITE` events? :)
If we would only reload on `CLOSE_WRITE`, we wouldn't have to debounce, thus allowing to reduce the latency for the reloading.

Btw, I noticed that since this was merged the code has [changed again](https://sourcegraph.com/github.com/emoon/dynamic_reload/-/commit/b45344d46b027c31116e8af6b0a1854f00a269fb#diff-dbc6c14dab3810ae2458b4bb5cb7b924R224) to use the debounced API, now it uses `NoticeWrite`, which is also triggered by `WRITE`. 
Could we please change back to only reloading on `CLOSE_WRITE` and `CREATE` (and then we won't have to debounce anymore)? :)

**Comment by Neopallium** [comment]
@Boscop Windows needs the reload on `WRITE`.  See the last commit.

**Comment by Boscop** [comment]
@Neopallium Do you mean [this commit](https://github.com/emoon/dynamic_reload/commit/46c3fe6b759107a03c77edf0f1802652d3dccf77) or which one?
I don't see any explanation. Why does Windows need the reload on `WRITE`?
Is there no way to get a `CLOSE_WRITE` event on Windows?

So you're saying debouncing is always necessary on Windows? 

But 2s is too long for livecoding user experience. What would be the longest time between write calls when rustc writes the dll file / what would be the shortest safe debounce time?

**Comment by Neopallium** [comment]
No.  I mean the last commit in this PR https://github.com/emoon/dynamic_reload/pull/14/commits/739694f5c1f81a656d874a2543a6b0e5572ed1f4

I don't remember the details, but I am sure that I tested it on a windows system (Win7) I had available at the time.

**Pull request merged**
