### PR TITLE
fix typo in lib.rs

### PR DESCRIPTION
**Pull request by benaryorg**
Just a little typo.

### CODE REVIEW

**Comment by benaryorg** [comment]
> Coverage decreased (-10.5%) to 85.89% when pulling 0815c67 **on benaryorg:benaryorg-patch-1** into a769e77 **on emoon:master**.

That can't be right.

**Comment by emoon** [comment]
Thanks!

**Comment by emoon** [comment]
> That can't be right.

It's not related to your changes but I'm not sure exactly why it happens.

**Comment by benaryorg** [comment]
> It's not related to your changes but I'm not sure exactly why it happens.

I think it is because of the new Rust version. Maybe.

**Comment by emoon** [comment]
Yeah that might be it.

**Pull request merged**
