### PR TITLE
Change to Debounce Watcher.

### PR DESCRIPTION
**Pull request by Neopallium**
Also ignore copy errors so copy can be retried 10 times.

Compare filename and extensions, to ignore .dll.exp file changes.

### CODE REVIEW

**Comment by Neopallium** [comment]
Nevermind, the crash was caused by a different change I was testing.  I was messing with the flags passed to dlopen(), trying to fix the issue with TLS.

**Comment by emoon** [comment]
Cool! Is this fine to merge now?

**Comment by Neopallium** [comment]
Yes.  This PR is safe to merge.  With this PR you can use TLS and `println!` in the plugin on Linux (should be ok on MacOS and windows too).

I have been working with `cr.h` to find the root cause of issues with reloading a library with TLS.  For now the work around is to just use different filenames (like the timestamp commit in this PR).  The library will not be unloaded even if `dlclose` is called, because `thread_local` variables with destructors registered haven't been run.  Which keeps references to the library preventing it from unloading.

The `cr-sys` crate is stable to use now.  I am looking into adding some features into `cr.h` to make it easier to use (like custom library symbols and better host-side notification load/unload/rollback/reload/etc..).

Once that work is done, it should be possible to change the `dynamic_reload` over to using `cr-sys` while still keeping the same API.  This will allow `cr.h` to handle the library reloads and verification.

**Comment by emoon** [comment]
Awesome! That sounds great.

**Pull request merged**
